#!/bin/sh

branch="$(git branch --show-current)"

# commits directly to master allowed only if no other branches present
master_branch_regex="^(master|main)$"
if [[ $branch =~ $master_branch_regex && `git branch --list -a` = '' ]]; then
  exit 0
fi

# prevent commits to wrongly named branches
valid_branch_regex="^(dev|feature|hotfix|bugfix|prerelease|release)\/[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
if [[ ! $branch =~ $valid_branch_regex ]]
then
    echo "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again." >&2
    exit 1
fi
