# ansible-playbook -i inventory.ini ubuntu_apt_upgrade.yml
---
- name: Install main applications
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: apt cache update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: install apps
      ansible.builtin.apt:
        name: 
          - htop
          - tmux
          - curl
          - mc
        state: present
